"""added the approval_status and rejection reason field

Revision ID: 2e6f302c4916
Revises: 863761ef7b1d
Create Date: 2026-06-27 21:19:48.349601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6f302c4916'
down_revision: Union[str, Sequence[str], None] = '863761ef7b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('approval_status', sa.Boolean(), nullable=False))
    op.add_column('venues', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'rejection_reason')
    op.drop_column('venues', 'approval_status')
    # ### end Alembic commands ###
