"""altered the category and amenity models to include name

Revision ID: 3e3350e86c24
Revises: 76a1df356ce1
Create Date: 2026-06-17 06:06:20.226804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3350e86c24'
down_revision: Union[str, Sequence[str], None] = '76a1df356ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amenities', sa.Column('name', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'amenities', ['name'])
    op.add_column('categories', sa.Column('name', sa.String(length=100), nullable=False))
    op.alter_column('categories', 'icon_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'categories', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.alter_column('categories', 'icon_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('categories', 'name')
    op.drop_constraint(None, 'amenities', type_='unique')
    op.drop_column('amenities', 'name')
    # ### end Alembic commands ###
