"""added the cleck user ID in the schema

Revision ID: 4c9a343c209f
Revises: a79725df5b17
Create Date: 2026-06-12 21:58:13.776698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9a343c209f'
down_revision: Union[str, Sequence[str], None] = 'a79725df5b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerkUserID', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_users_clerkUserID'), 'users', ['clerkUserID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_clerkUserID'), table_name='users')
    op.drop_column('users', 'clerkUserID')
    # ### end Alembic commands ###
