"""added the categories, amentites, and venue table

Revision ID: 6ef22806f76f
Revises: 0f3e63860a01
Create Date: 2026-06-16 18:37:18.217188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ef22806f76f'
down_revision: Union[str, Sequence[str], None] = '0f3e63860a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('admin', 'member', 'moderator', name='userrole'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
