"""altered the category and amenity table to include icon_name

Revision ID: 76a1df356ce1
Revises: 51307cd3d598
Create Date: 2026-06-17 05:46:54.210066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a1df356ce1'
down_revision: Union[str, Sequence[str], None] = '51307cd3d598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amenities', sa.Column('icon_name', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('amenities_image_key'), 'amenities', type_='unique')
    op.drop_constraint(op.f('amenities_name_key'), 'amenities', type_='unique')
    op.create_unique_constraint(None, 'amenities', ['icon_name'])
    op.drop_column('amenities', 'name')
    op.drop_column('amenities', 'image')
    op.add_column('categories', sa.Column('icon_name', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('categories_image_key'), 'categories', type_='unique')
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.create_unique_constraint(None, 'categories', ['icon_name'])
    op.drop_column('categories', 'name')
    op.drop_column('categories', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('categories_image_key'), 'categories', ['image'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'icon_name')
    op.add_column('amenities', sa.Column('image', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('amenities', sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'amenities', type_='unique')
    op.create_unique_constraint(op.f('amenities_name_key'), 'amenities', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('amenities_image_key'), 'amenities', ['image'], postgresql_nulls_not_distinct=False)
    op.drop_column('amenities', 'icon_name')
    # ### end Alembic commands ###
