"""created the updateed_at and created_at columns for venue

Revision ID: 863761ef7b1d
Revises: e4a5e12bc8c8
Create Date: 2026-06-27 15:56:20.824727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863761ef7b1d'
down_revision: Union[str, Sequence[str], None] = 'e4a5e12bc8c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('hourly_rent', sa.Integer(), nullable=False))
    op.add_column('venues', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('venues', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'updated_at')
    op.drop_column('venues', 'created_at')
    op.drop_column('venues', 'hourly_rent')
    # ### end Alembic commands ###
