"""created the owner's model

Revision ID: a79725df5b17
Revises: 1c6898cf07a1
Create Date: 2026-06-11 20:25:48.952810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79725df5b17'
down_revision: Union[str, Sequence[str], None] = '1c6898cf07a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profession', sa.String(length=100), nullable=False),
    sa.Column('promise', sa.Text(), nullable=False),
    sa.Column('intro_descp', sa.Text(), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('venues_listed', sa.Integer(), nullable=False),
    sa.Column('overall_ratting', sa.Integer(), nullable=False),
    sa.Column('joined_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    # ### end Alembic commands ###
