"""established the venue table completely

Revision ID: e4a5e12bc8c8
Revises: ec2c80ca3b97
Create Date: 2026-06-21 18:33:33.784680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a5e12bc8c8'
down_revision: Union[str, Sequence[str], None] = 'ec2c80ca3b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('venues', sa.Column('max_capacity', sa.Integer(), nullable=False))
    op.add_column('venues', sa.Column('city', sa.String(length=255), nullable=False))
    op.add_column('venues', sa.Column('district', sa.String(length=255), nullable=False))
    op.add_column('venues', sa.Column('state', sa.String(length=255), nullable=False))
    op.add_column('venues', sa.Column('country', sa.String(length=255), nullable=False))
    op.add_column('venues', sa.Column('location_url', sa.Text(), nullable=False))
    op.add_column('venues', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('venues', sa.Column('cover_image', sa.Text(), nullable=False))
    op.add_column('venues', sa.Column('cancellation', sa.Boolean(), nullable=False))
    op.add_column('venues', sa.Column('cancellation_percentage', sa.Integer(), nullable=False))
    op.add_column('venues', sa.Column('street_address', sa.Text(), nullable=False))
    op.add_column('venues', sa.Column('minimum_slot_duration', sa.Integer(), nullable=False))
    op.add_column('venues', sa.Column('cancellation_time_limit', sa.Integer(), nullable=False))
    op.add_column('venues', sa.Column('total_reviews', sa.Integer(), nullable=False))
    op.add_column('venues', sa.Column('overall_rating', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('venues', sa.Column('gallery', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'gallery')
    op.drop_column('venues', 'overall_rating')
    op.drop_column('venues', 'total_reviews')
    op.drop_column('venues', 'cancellation_time_limit')
    op.drop_column('venues', 'minimum_slot_duration')
    op.drop_column('venues', 'street_address')
    op.drop_column('venues', 'cancellation_percentage')
    op.drop_column('venues', 'cancellation')
    op.drop_column('venues', 'cover_image')
    op.drop_column('venues', 'description')
    op.drop_column('venues', 'location_url')
    op.drop_column('venues', 'country')
    op.drop_column('venues', 'state')
    op.drop_column('venues', 'district')
    op.drop_column('venues', 'city')
    op.drop_column('venues', 'max_capacity')
    op.drop_column('venues', 'name')
    # ### end Alembic commands ###
