"""established a one-to-many connection of owner with venues

Revision ID: ec2c80ca3b97
Revises: 3e3350e86c24
Create Date: 2026-06-21 15:41:10.268420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2c80ca3b97'
down_revision: Union[str, Sequence[str], None] = '3e3350e86c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venues', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_column('venues', 'owner_id')
    # ### end Alembic commands ###
